### ISSUE TITLE
Culerity not working with regular JRuby

### ISSUE THREAD

**Issue by gurdotan** [langalex/culerity#28]
I'm trying to get Culerity working with a regular installation of JRuby (installed with apt-get on Ubuntu).

I followed all steps in the rdoc, fired up rake culerity:rails:start and I still get the following error:

/usr/lib/jruby//lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require': no such file to load -- culerity/celerity_server (LoadError)
        from /usr/lib/jruby//lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /var/lib/gems/1.8/gems/culerity-0.2.12/lib/start_celerity.rb:2

AAHHHH!!!!!!
Any ideas?  Thanks...

**Comment by langalex** [comment]
looks like it can't find culerity itself. are you using bundler or something? rvm?

**Comment by phoet** [comment]
i am trying to get cucumber tests working with culerity and rvm and i saw that error too:

/Users/nofail/.rvm/rubies/jruby-1.5.2/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require': no such file to load -- culerity/celerity_server (LoadError)
    from /Users/nofail/.rvm/rubies/jruby-1.5.2/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /Users/nofail/.rvm/gems/ruby-1.8.7-p302@tolingo-site/gems/culerity-0.2.12/lib/start_celerity.rb:2

seems not to happen with culerity culerity-0.2.10, though i have other issues with that...

**Comment by ghost** [comment]
I am having the same problem.  0.2.10 works, but when I switch to 0.2.12 I encounter the same error.  I'm using bundler, but that's not a factor, since 0.2.10 works fine with bundler.

**Comment by tinomen** [comment]
I had this problem with culerity and bundler. The new way to start the celerity server relies on rubygems which aren't shared by MRI and jruby and that's why you see this message. Also, bundler sets the RUBYOPT environment var which gets shared with the IO#popen call so jruby gets confused about it's environment. There is a pull request and patch in issue #32 (https://github.com/langalex/culerity/issues#issue/32) that solves this and other issues.

**Comment by langalex** [comment]
just released 0.2.15, which includes the mentioned fix. does that fix your issues?

**Comment by tinomen** [comment]
This is working for me.
